INSERT INTO `SP_EVENTS` (`UID`, `IDPARENT`, `NAME`, `TABNAME`) VALUES (NULL, '0', 'Ипотека', NULL);
INSERT INTO `SP_EVENTS` (`UID`, `IDPARENT`, `NAME`, `TABNAME`) VALUES (NULL, '38', 'Отправлен запрос по ипотеке', 'wrk_ipotekarequest');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '39', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '39', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '39', '3');