INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '18', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '18', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '18', '6');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '25', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '25', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '25', '6');