-- Показы
--  Показ создан
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '9', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '9', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '9', '3');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '9', '4');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '9', '5');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '9', '6');
--  Показ состоялся
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '10', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '10', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '10', '3');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '10', '4');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '10', '5');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '10', '6');
--  Показ не состоялся
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '11', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '11', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '11', '3');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '11', '4');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '11', '5');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '11', '6');