INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '31', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '31', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '31', '6');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '37', '1');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '37', '2');
INSERT INTO `SP_EVENT_PERSON` (`UID`, `IDEVENT`, `IDPERSONTYPE`) VALUES (NULL, '37', '6');