DELIMITER $$
CREATE DEFINER=`stastrjn_nrn`@`localhost` PROCEDURE `ADD_MESSAGE`(IN `INIDFROM` INT, IN `INIDTO` INT, IN `INBODY` TEXT)
BEGIN
 DECLARE sBODY text;
 -- Обработка тела сообщения
 SET sBODY = INBODY;
 INSERT INTO messages (IDFROM,IDTO,BODY) values (INIDFROM,INIDTO,sBODY);
END$$
DELIMITER ;