DELIMITER $$
CREATE DEFINER=`stastrjn_nrn`@`localhost` PROCEDURE `WRK_DOBR`(IN `INPERSONTYPEID` INT, IN `INAGENTID` INT, IN `INEVENTPARAMS` VARCHAR(50), IN `INACTIONTYPEID` INT, IN `INACTIONTEMPLATE` TEXT, IN `INACTIONPARAMS` VARCHAR(200), IN `INEVENTUID` VARCHAR(36))
BEGIN
  DECLARE sBody text;
  SET sBody = 	WRK_CREATEMSGBODY2EVENT(INACTIONTEMPLATE,INEVENTUID);
  -- Выполняем соответствующее действие
  -- CALL ADD_2TMPDEBUGLOG (concat('Событие ',EVID)); -- ОТЛАДКА!!

  CASE INACTIONTYPEID 
  WHEN 1 THEN call ADD_MESSAGE(32,INAGENTID,sBody);
   
  END CASE;
 
 

END$$
DELIMITER ;