DROP PROCEDURE `WRK_CLOSETASK4ZAKAZ`;
DELIMITER $$
CREATE DEFINER=`stastrjn_nrn`@`localhost` PROCEDURE `WRK_CLOSETASK4ZAKAZ`(IN `INZAKAZ` INT, IN `INTABLE` VARCHAR(30))
BEGIN
DECLARE iFirmid int;
  SET iFirmid = GET_AGENCY4ZAKAZ(INZAKAZ,INTABLE);
  UPDATE task tt set tt.ISCOMPLETE = 1, tt.ISAUDITED = 1 where tt.AGENCYID = iFirmid and tt.SUBJECTID = INZAKAZ and tt.TABNAME = INTABLE;
END$$
DELIMITER ;

